baseURL = "https://go-masonry.github.io/"
languageCode = "en-us"
title = "Mortar Documentation"

theme = "docuport"

[params]
color_main="blue"
color_second="#68829E"

# Code highlight configuration
[markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineAnchors = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "friendly"
    tabWidth = 4

[[menu.shortcuts]]
name = "Github"
identifier = "mortar"
url = "https://github.com/go-masonry/mortar"
weight = 20

[[menu.shortcuts]]
name = "Demo"
identifier = "demo"
url = "https://github.com/go-masonry/mortar-demo"
weight = 10

[[menu.shortcuts]]
name = "Discussions"
identifier = "discussions"
url = "https://github.com/go-masonry/mortar/discussions"
weight = 30